FROM python:3.12-slim
WORKDIR /app

RUN apt-get update && apt-get install -y gcc procps

# Install aussrc_tools and requirements with CASA
COPY pyproject.toml README.md ./
COPY src ./src
RUN pip install --upgrade pip && pip install ".[casa]"
RUN pip install --index-url=https://go.nrao.edu/pypi casadata
