[path]

# Full path to SoFiAX installation directory without trailing slash
# (e.g. /usr/local/SoFiAX)
sofiax_base_dir    =  /path/to/SoFiAX/base/directory
# Full path to SoFiA 2 executable
# (e.g. /usr/bin/sofia)
sofia2_executable  =  /path/to/SoFiA-2/executable


[database]

# Host name of database server
# (e.g. localhost or my.server.org)
db_host            =  hostname
# Database name
db_name            =  database
# User name
db_user            =  username
# Password
db_pass            =  password


[boundary]

# Boundaries of the input data cube to be processed
# (use 0 and 99999 for min and max to select full cube)
x_min              =  300
x_max              =  4300
y_min              =  300
y_max              =  4300
z_min              =  750
z_max              =  6616


[region]

# Desired sub-cube size and spatial/spectral overlap
subcube_shape      =  1500 1500 1400
min_overlap_spat   =  256
min_overlap_spec   =  256


[pipeline]

# Number of CPU cores to be used per task
cpu_cores          =  8

# Position tolerance for cross-matching of sources in overlap regions
# in multiples of the uncertainty
# Sources with positions (x,y,z) that fall within that threshold will
# be considered as identical and be subjected to additional sanity checking
tolerance_pos      =  5

# Settings for sanity checking of cross-matched sources in overlap regions
# Ellipse fit major and minor axis tolerances in percent
# If the relative difference in major and minor axis sizes between two sources
# with matching positions exceeds these tolerances, they will be flagged for
# manual resolution
tolerance_spat     =  80,80
# w20 and w50 line width tolerances in percent
# If the relative difference in w20 and w50 line widths between two sources
# with matching positions exceeds these tolerances, they will be flagged for
# manual resolution
tolerance_spec     =  50,50
# Flux tolerance in percent
# If the relative flux difference between two sources with matching positions
# exceeds this tolerance, they will be flagged for manual resolution
tolerance_flux     =  30
