name: cicd
on:
  [push, pull_request]
steps:
  - uses: actions/checkout@v5
    with:
      submodules: true
  - uses: ./python-templates/.github/workflows/ci.yml
    with:
      python-version: 3.12
      cache: 'pip'
