name: Docker build release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  metadata:
    runs-on: ubuntu-latest
    steps:
      - name: Set release version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Build the Docker image
        uses: actions/checkout@v2
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin docker.io
          docker build metadata --tag docker.io/${{ secrets.DOCKERHUB_USERNAME }}/metadata_tools:$RELEASE_VERSION
          docker push docker.io/${{ secrets.DOCKERHUB_USERNAME }}/metadata_tools:$RELEASE_VERSION