name: Docker build latest

on: [push, pull_request]

jobs:
  metadata:
    runs-on: ubuntu-latest
    steps:
      - name: Build the Docker image
        uses: actions/checkout@v2
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin docker.io
          docker build metadata --tag docker.io/${{ secrets.DOCKERHUB_USERNAME }}/metadata_tools:latest
          docker push docker.io/${{ secrets.DOCKERHUB_USERNAME }}/metadata_tools:latest