name: Tests
on: [push, pull_request]
jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    # TODO: cache dependencies
    - name: Generate report
      run: |
        pip install pytest pytest-cov
        pytest --cov-report xml --cov=tests/
    - uses: codecov/codecov-action@v3
      with:
        files: ./coverage.xml,
        verbose: true

  tests:
    runs-on: ubuntu-latest
    env:
      CASDA_USERNAME: ${{ secrets.CASDA_USERNAME }}
      CASDA_PASSWORD: ${{ secrets.CASDA_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.0'
          architecture: 'x64'
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-build-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}
      - run: pip3 install -r tests/requirements.txt
      - run: pytest tests

  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.0'
          architecture: 'x64'
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-build-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}
      - run: pip3 install flake8
      - run: flake8 .