name: Tests
on: [push, pull_request]

jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    # TODO: cache dependencies
    - name: Generate report
      run: |
        pip install pytest pytest-cov
        pytest --cov-report xml --cov=tests/
    - uses: codecov/codecov-action@v3
      with:
        files: ./coverage.xml,
        verbose: true

  tests:
    runs-on: ubuntu-latest
    env:
      CASDA_USERNAME: ${{ secrets.CASDA_USERNAME }}
      CASDA_PASSWORD: ${{ secrets.CASDA_PASSWORD }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      - run: |
          pip install -r tests/requirements.txt
          pytest tests

  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      - run: |
          pip install flake8
          flake8 .